/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eneim' at '1/27/15 2:24 PM' with Gradle 1.12
 *
 * @author eneim, @date 1/27/15 2:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
